version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - php
#      - mysql
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: .
#    links:
#      - mysql
    volumes:
      - .:/var/www
#  mysql:
#    image: mysql
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: password
